name: Refactor (internal)
description: For internal use only.
labels: ['type:refactor', 'status:requirements', 'priority-5-triage']
body:
  - type: textarea
    id: describe-the-proposed-refactor
    attributes:
      label: Describe the proposed refactor.
    validations:
      required: true
